openapi: 3.2.0
info:
  title: Ascribe Coder Responses API
  description: To import this API to Postman, copy the URL from the top of this page.
  contact:
    email: support@goascribe.com
  version: v2
servers:
- url: https://api.goascribe.us/coder/v2
  description: US Servers
- url: https://api.goascribe.eu/coder/v2
  description: EU Servers
- url: https://api-ca.goascribe.com/coder/v2
  description: CA Servers
security:
- Bearer: []
tags:
- name: Responses
paths:
  /Responses/{QuestionKey}/{RespondentID}:
    delete:
      tags:
      - Responses
      summary: Delete a response from the database by using pair of question key and…
      description: Method deletes the response by using question key and respondent id.
      parameters:
      - name: QuestionKey
        in: path
        description: Key of question
        required: true
        schema:
          type: integer
          format: int32
      - name: RespondentID
        in: path
        description: ID of respondent
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponseResponse'
              example:
                errorMessage: null
      operationId: deleteResponsesByQuestionKeyByRespondentID
      x-operation-id-source: derived
  /Responses/Batch:
    delete:
      tags:
      - Responses
      summary: Delete a batch of responses from the database by using pairs of question key…
      description: Method deletes a batch of responses by using pairs of question key and respondent id.
      requestBody:
        description: Array of pairs of question key and respondent id.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteResponsesBatchRequest'
            example:
              questionResponses:
              - questionKey: 55
                respondentIDs:
                - '100001'
                - '100002'
              - questionKey: 56
                respondentIDs:
                - '200001'
              - questionKey: 57
                respondentIDs:
                - '300001'
                - '300002'
                - '300003'
          text/json:
            schema:
              $ref: '#/components/schemas/DeleteResponsesBatchRequest'
            example:
              questionResponses:
              - questionKey: 55
                respondentIDs:
                - '100001'
                - '100002'
              - questionKey: 56
                respondentIDs:
                - '200001'
              - questionKey: 57
                respondentIDs:
                - '300001'
                - '300002'
                - '300003'
          application/*+json:
            schema:
              $ref: '#/components/schemas/DeleteResponsesBatchRequest'
            example:
              questionResponses:
              - questionKey: 55
                respondentIDs:
                - '100001'
                - '100002'
              - questionKey: 56
                respondentIDs:
                - '200001'
              - questionKey: 57
                respondentIDs:
                - '300001'
                - '300002'
                - '300003'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponsesBatchResponse'
              example:
                questionResponses:
                - questionKey: 55
                  respondentID: '100001'
                  errorMessage: null
                - questionKey: 55
                  respondentID: '100002'
                  errorMessage: null
                - questionKey: 56
                  respondentID: '200001'
                  errorMessage: null
                - questionKey: 57
                  respondentID: '300001'
                  errorMessage: 'SQL Exception: Cannot delete. Trigger TR_Responses_BeforeDeleteCheck.'
                - questionKey: 57
                  respondentID: '300002'
                  errorMessage: null
                - questionKey: 57
                  respondentID: '300003'
                  errorMessage: null
                errorMessage: null
      operationId: deleteResponsesBatch
      x-operation-id-source: derived
  /Responses/{questionKey}:
    get:
      tags:
      - Responses
      summary: Get the Responses in the specified Question
      description: 'For coded responses the keys of the applied codes are returned for each response.


        These keys can be matched to the keys of the codes returned in a query for the codebook to find the details of each of the applied codes.


        The optional date query parameters are UTC date/time values.


        These should be specified in the form:


        YYYY-MM-DDThh:mm:ss


        Where the hour ranges from 0 to 23. For example:


        2020-02-23T16:05:17


        If the time portion of the date/time value is omitted it is assumed to be 00:00:00 GMT.'
      parameters:
      - name: questionKey
        in: path
        description: The key of the Question, which must be an integer value.
        required: true
        schema:
          type: integer
          format: int32
      - name: includeText
        in: query
        description: "If true, the text of each Response is returned.\n\n            If false or omitted the text is not returned."
        schema:
          type: boolean
          default: false
      - name: status
        in: query
        description: 'If omitted, all Responses for the Question are returned.


          If present, one of these values:

          <ul><li>coded: return only Responses with at least one Code applied.

          </li><li>uncoded: return only Responses with no Code applied.</li></ul>'
        schema:
          type: string
      - name: codedAfter
        in: query
        description: If present, only responses with a code applied on or after the specified date/time are returned.
        schema:
          type: string
          format: date-time
      - name: codedBefore
        in: query
        description: If present, only responses with a code applied before the specified date/time are returned.
        schema:
          type: string
          format: date-time
      - name: loadedAfter
        in: query
        description: If present, only responses loaded on or after the specified date/time are returned.
        schema:
          type: string
          format: date-time
      - name: loadedBefore
        in: query
        description: If present, only responses loaded before the specified date/time are returned.
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResponsesResponse'
              example:
                responses:
                - rid: 34-22907
                  text: I do not like the red color
                  transcription: null
                  translation: null
                  notes: null
                  codeKeys:
                  - 4978
                  - 886
                - rid: 34-22988
                  text: This is a fantastic product
                  transcription: null
                  translation: null
                  notes: null
                  codeKeys:
                  - 449
                errorMessage: null
      operationId: getResponsesByQuestionKey
      x-operation-id-source: derived
    post:
      tags:
      - Responses
      summary: Add Responses to a Question
      description: 'This operation will add new responses to the specified question, optionally autocoding them. It will never modify existing responses.


        For each QuestionResponse submitted, if the question does not have a response stored in Ascribe with the specified respondent id,


        then the response will be added.


        Otherwise, the Response stored in Ascribe will not be modified. The QuestionResponse submitted will be ignored,


        and any codes that have been applied to the Response will be unchanged.


        This operation allows the use of a Rule Set to modify or veto the Responses submitted, and automatically coding the responses as they are added.'
      parameters:
      - name: questionKey
        in: path
        description: The key of the question, which must be an integer value
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        description: The responses to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostResponsesRequest'
            example:
              responses:
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22907
                verbatim: I do not like the red color
                translation: null
                transcription: null
                notes: null
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22988
                verbatim: This is a fantastic product
                translation: null
                transcription: null
                notes: null
              autoCodeTextMatch: false
              autoCodeInputId: false
              autoCodeByRegex: false
          text/json:
            schema:
              $ref: '#/components/schemas/PostResponsesRequest'
            example:
              responses:
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22907
                verbatim: I do not like the red color
                translation: null
                transcription: null
                notes: null
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22988
                verbatim: This is a fantastic product
                translation: null
                transcription: null
                notes: null
              autoCodeTextMatch: false
              autoCodeInputId: false
              autoCodeByRegex: false
          application/*+json:
            schema:
              $ref: '#/components/schemas/PostResponsesRequest'
            example:
              responses:
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22907
                verbatim: I do not like the red color
                translation: null
                transcription: null
                notes: null
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22988
                verbatim: This is a fantastic product
                translation: null
                transcription: null
                notes: null
              autoCodeTextMatch: false
              autoCodeInputId: false
              autoCodeByRegex: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponsesResponse'
              example:
                codebookKey: 86443
                responsesAdded: 2
                existingResponsesUnchanged: 0
                responsesCoded: 0
                responsesCodedByTextMatch: 0
                responsesCodedByInputId: 0
                responsesCodedByRegex: 0
                addedResponses:
                - codes:
                  - codeKey: 200404044
                    description: Red
                  rid: 34-22907
                  verbatim: null
                  translation: null
                  transcription: null
                  notes: null
                - codes: []
                  rid: 34-22988
                  verbatim: null
                  translation: null
                  transcription: null
                  notes: null
                errorMessage: null
      operationId: postResponsesByQuestionKey
      x-operation-id-source: derived
    put:
      tags:
      - Responses
      summary: Add or update Responses in the specified Question
      description: 'If the Question does not have a Response stored in Ascribe with the specified respondent id, then the response will be added.


        Otherwise, the Response stored in Ascribe will be updated if any of the properties of in the request differ from the values of the current properties of the Response.'
      parameters:
      - name: questionKey
        in: path
        description: The key of the Question, which must be an integer value.
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        description: The Responses to add or update.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutResponsesRequest'
            example:
              responses:
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22907
                verbatim: I do not like the red color
                translation: null
                transcription: null
                notes: null
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22988
                verbatim: This is a fantastic product
                translation: null
                transcription: null
                notes: null
              codingMethod: 0
              allowEmptyStrings: false
          text/json:
            schema:
              $ref: '#/components/schemas/PutResponsesRequest'
            example:
              responses:
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22907
                verbatim: I do not like the red color
                translation: null
                transcription: null
                notes: null
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22988
                verbatim: This is a fantastic product
                translation: null
                transcription: null
                notes: null
              codingMethod: 0
              allowEmptyStrings: false
          application/*+json:
            schema:
              $ref: '#/components/schemas/PutResponsesRequest'
            example:
              responses:
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22907
                verbatim: I do not like the red color
                translation: null
                transcription: null
                notes: null
              - appliedcodes: null
                segmentcodes: null
                rid: 34-22988
                verbatim: This is a fantastic product
                translation: null
                transcription: null
                notes: null
              codingMethod: 0
              allowEmptyStrings: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutResponsesResponse'
              example:
                responsesAdded: 10
                existingResponsesUpdated: 15
                existingResponsesUnchanged: 5
                responsesCoded: 0
                errorMessage: null
      operationId: putResponsesByQuestionKey
      x-operation-id-source: derived
  /Responses/{studyKey}/Batch:
    post:
      tags:
      - Responses
      summary: Add Responses to the specified Study's Questions
      description: 'This operation will add new responses to the specified study''s questions.


        For each of question it will work absolutely the same way as POST /Responses/{questionKey} method does.'
      parameters:
      - name: studyKey
        in: path
        description: The key of the study, which must be an integer value
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        description: The responses to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostResponsesBatchRequest'
            example:
              questionResponses:
              - questionKey: 212345
                responses:
                - rid: 34-22907
                  verbatim: I do not like the red color
                  translation: null
                  transcription: null
                  notes: null
                - rid: 34-22988
                  verbatim: This is a fantastic product
                  translation: null
                  transcription: null
                  notes: null
              - questionKey: 212346
                responses:
                - rid: 34-22907
                  verbatim: France
                  translation: null
                  transcription: null
                  notes: null
                - rid: 34-22988
                  verbatim: USA
                  translation: null
                  transcription: null
                  notes: null
          text/json:
            schema:
              $ref: '#/components/schemas/PostResponsesBatchRequest'
            example:
              questionResponses:
              - questionKey: 212345
                responses:
                - rid: 34-22907
                  verbatim: I do not like the red color
                  translation: null
                  transcription: null
                  notes: null
                - rid: 34-22988
                  verbatim: This is a fantastic product
                  translation: null
                  transcription: null
                  notes: null
              - questionKey: 212346
                responses:
                - rid: 34-22907
                  verbatim: France
                  translation: null
                  transcription: null
                  notes: null
                - rid: 34-22988
                  verbatim: USA
                  translation: null
                  transcription: null
                  notes: null
          application/*+json:
            schema:
              $ref: '#/components/schemas/PostResponsesBatchRequest'
            example:
              questionResponses:
              - questionKey: 212345
                responses:
                - rid: 34-22907
                  verbatim: I do not like the red color
                  translation: null
                  transcription: null
                  notes: null
                - rid: 34-22988
                  verbatim: This is a fantastic product
                  translation: null
                  transcription: null
                  notes: null
              - questionKey: 212346
                responses:
                - rid: 34-22907
                  verbatim: France
                  translation: null
                  transcription: null
                  notes: null
                - rid: 34-22988
                  verbatim: USA
                  translation: null
                  transcription: null
                  notes: null
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponsesBatchResponse'
              example:
                questionResponses:
                - questionKey: 1001
                  questionId: Q1
                  addedResponses:
                  - rid: 34-22907
                    verbatim: I do not like the red color
                    translation: null
                    transcription: null
                    notes: null
                  - rid: 34-22988
                    verbatim: This is a fantastic product
                    translation: null
                    transcription: null
                    notes: null
                - questionKey: 1002
                  questionId: Q2
                  addedResponses:
                  - rid: 34-22907
                    verbatim: France
                    translation: null
                    transcription: null
                    notes: null
                  - rid: 34-22988
                    verbatim: USA
                    translation: null
                    transcription: null
                    notes: null
                errorMessage: null
      operationId: postResponsesByStudyKeyBatch
      x-operation-id-source: derived
    put:
      tags:
      - Responses
      summary: Add or update Responses to the specified Study's Questions
      parameters:
      - name: studyKey
        in: path
        description: Key of study
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        description: The study questions and their responses to update/add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutResponsesBatchRequest'
            example:
              questionResponses:
              - questionKey: 200011
                responses:
                - rid: ABC_12345
                  verbatim: I do not like the red color
                  translation: null
                  transcription: null
                  notes: null
                - rid: ABC_12346
                  verbatim: This is a fantastic product
                  translation: null
                  transcription: null
                  notes: null
              - questionKey: 200012
                responses:
                - rid: ABC_12345
                  verbatim: Very good
                  translation: null
                  transcription: null
                  notes: null
                - rid: ABC_12346
                  verbatim: I can't answer this question
                  translation: null
                  transcription: null
                  notes: null
                - rid: ABC_12347
                  verbatim: If it has green color, it would be better
                  translation: null
                  transcription: null
                  notes: null
              allowEmptyStrings: false
          text/json:
            schema:
              $ref: '#/components/schemas/PutResponsesBatchRequest'
            example:
              questionResponses:
              - questionKey: 200011
                responses:
                - rid: ABC_12345
                  verbatim: I do not like the red color
                  translation: null
                  transcription: null
                  notes: null
                - rid: ABC_12346
                  verbatim: This is a fantastic product
                  translation: null
                  transcription: null
                  notes: null
              - questionKey: 200012
                responses:
                - rid: ABC_12345
                  verbatim: Very good
                  translation: null
                  transcription: null
                  notes: null
                - rid: ABC_12346
                  verbatim: I can't answer this question
                  translation: null
                  transcription: null
                  notes: null
                - rid: ABC_12347
                  verbatim: If it has green color, it would be better
                  translation: null
                  transcription: null
                  notes: null
              allowEmptyStrings: false
          application/*+json:
            schema:
              $ref: '#/components/schemas/PutResponsesBatchRequest'
            example:
              questionResponses:
              - questionKey: 200011
                responses:
                - rid: ABC_12345
                  verbatim: I do not like the red color
                  translation: null
                  transcription: null
                  notes: null
                - rid: ABC_12346
                  verbatim: This is a fantastic product
                  translation: null
                  transcription: null
                  notes: null
              - questionKey: 200012
                responses:
                - rid: ABC_12345
                  verbatim: Very good
                  translation: null
                  transcription: null
                  notes: null
                - rid: ABC_12346
                  verbatim: I can't answer this question
                  translation: null
                  transcription: null
                  notes: null
                - rid: ABC_12347
                  verbatim: If it has green color, it would be better
                  translation: null
                  transcription: null
                  notes: null
              allowEmptyStrings: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutResponsesBatchResponse'
              example:
                questionResponses:
                - questionKey: 1
                  questionId: Q1
                  updatedResponses:
                  - rid: ABC_12345
                    verbatim: I do not like the red color
                    translation: null
                    transcription: null
                    notes: null
                  - rid: ABC_12346
                    verbatim: This is a fantastic product
                    translation: null
                    transcription: null
                    notes: null
                  addedResponses: []
                  unchangedResponses: []
                  errorMessage: null
                - questionKey: 2
                  questionId: Q2
                  updatedResponses:
                  - rid: ABC_12345
                    verbatim: I do not like the red color
                    translation: null
                    transcription: null
                    notes: null
                  - rid: ABC_12346
                    verbatim: This is a fantastic product
                    translation: null
                    transcription: null
                    notes: null
                  addedResponses:
                  - rid: ABC_12347
                    verbatim: If it has green color, it would be better
                    translation: null
                    transcription: null
                    notes: null
                  unchangedResponses: []
                  errorMessage: null
                errorMessage: null
      operationId: putResponsesByStudyKeyBatch
      x-operation-id-source: derived
components:
  schemas:
    DeleteQuestionResponseResultItem:
      type: object
      properties:
        questionKey:
          type: integer
          description: Key of question
          format: int32
        respondentID:
          type:
          - string
          - 'null'
          description: Respondent ID of response
        errorMessage:
          type:
          - string
          - 'null'
          description: Error message why response can not be deleted
      additionalProperties: false
      description: Result item with information about status of deletion of some response in the specified question
    PutResponsesRequest:
      required:
      - responses
      type: object
      properties:
        responses:
          type: array
          items:
            $ref: '#/components/schemas/PutResponse'
          description: 'The responses to be added or updated.


            All strings in these responses will be trimmed of leading and trailing white space.'
        codingMethod:
          type: integer
          description: 'Method of coding to use for this request.

            '
          format: int32
        allowEmptyStrings:
          type: boolean
          description: "When it is true it allows setting empty string as value for verbatim/translation/transcription/notes fields. \nOtherwise empty string is ignored (i.e. it works like null value). By default it is false."
      additionalProperties: false
      description: A request to add Responses to the specified Question, or to update existing Responses.
    PostResponsesBatchRequest:
      required:
      - questionResponses
      type: object
      properties:
        questionResponses:
          type: array
          items:
            $ref: '#/components/schemas/PostQuestionResponses'
          description: Array of questions with their responses to create
      additionalProperties: false
      description: Request with information for creating multiple responses via one API call (batch operation)
    PostQuestionResponses:
      required:
      - questionKey
      - responses
      type: object
      properties:
        questionKey:
          type: integer
          description: Key of target question
          format: int32
        responses:
          type: array
          items:
            $ref: '#/components/schemas/PostResponseBatch'
          description: Responses
      additionalProperties: false
      description: Question's responses to post
    PutResponsesBatchResult:
      required:
      - questionId
      - questionKey
      type: object
      properties:
        questionKey:
          type: integer
          description: Key of target question
          format: int32
        questionId:
          type:
          - string
          - 'null'
          description: Id of target question
        updatedResponses:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PutResponseBatch'
          description: Updated responses
        addedResponses:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PutResponseBatch'
          description: Added responses
        unchangedResponses:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PutResponseBatch'
          description: Unchanged responses
        errorMessage:
          type:
          - string
          - 'null'
          description: Error message when updating question responses finished with some error
      additionalProperties: false
      description: Class contains information about updated responses for target questions
    PutResponseBatch:
      required:
      - rid
      type: object
      properties:
        rid:
          minLength: 1
          type: string
          description: 'The respondent id, which is unique among Responses in this Question.


            This id identifies the respondent in the Study, and that respondent''s Response in this Question.'
        verbatim:
          type:
          - string
          - 'null'
          description: 'The verbatim text of the response, in other words the answer the respondent gave to the question posed.


            Required if this is a new respondent, optional if updating an existing response for this respondent.'
        translation:
          type:
          - string
          - 'null'
          description: Optional translation of the verbatim text.
        transcription:
          type:
          - string
          - 'null'
          description: Optional transcription of the response.
        notes:
          type:
          - string
          - 'null'
          description: Optional notes associated with the response.
      additionalProperties: false
      description: Response class for presenting study response data in the request for PUT BATCH operation.
    AddedResponseWithCodingInfo:
      required:
      - codes
      - rid
      type: object
      properties:
        rid:
          minLength: 1
          type: string
          description: 'The respondent id, which is unique among Responses in this Question.


            This id identifies the respondent in the Study, and that respondent''s Response in this Question.'
        verbatim:
          type:
          - string
          - 'null'
          description: 'The verbatim text of the response, in other words the answer the respondent gave to the question posed.


            Required if this is a new respondent, optional if updating an existing response for this respondent.'
        translation:
          type:
          - string
          - 'null'
          description: Optional translation of the verbatim text.
        transcription:
          type:
          - string
          - 'null'
          description: Optional transcription of the response.
        notes:
          type:
          - string
          - 'null'
          description: Optional notes associated with the response.
        codes:
          type: array
          items:
            $ref: '#/components/schemas/AddedCode'
          description: The codes automatically applied to the response.
      additionalProperties: false
      description: Added response with coding info
    PutResponsesBatchRequest:
      required:
      - questionResponses
      type: object
      properties:
        questionResponses:
          type: array
          items:
            $ref: '#/components/schemas/PutQuestionResponses'
          description: Array of questions with their responses to update
        allowEmptyStrings:
          type: boolean
          description: "When it is true it allows setting empty string as value for verbatim/translation/transcription/notes fields. \nOtherwise empty string is ignored (i.e. it works like null value). By default it is false."
      additionalProperties: false
      description: Request with inforamtion for updating multiple responses via one API call (batch operation)
    PostResponsesResponse:
      required:
      - addedResponses
      - codebookKey
      - existingResponsesUnchanged
      - responsesAdded
      - responsesCoded
      - responsesCodedByInputId
      - responsesCodedByRegex
      - responsesCodedByTextMatch
      type: object
      properties:
        errorMessage:
          type:
          - string
          - 'null'
        codebookKey:
          type: integer
          description: The key of the Codebook for this Question.
          format: int32
        responsesAdded:
          type: integer
          description: 'The count of Responses added to the Question.


            This is the number of responses in the PutResponsesRequest that had rid values that were not already present in this Question.'
          format: int32
        existingResponsesUnchanged:
          type: integer
          description: 'The count of existing Responses unchanged.


            This is the number of responses in the PutResponsesRequest that had rid values that were already present in this Question.'
          format: int32
        responsesCoded:
          type: integer
          description: 'The count of responses coded.

            '
          format: int32
        responsesCodedByTextMatch:
          type: integer
          description: 'The count of responses coded by text match.


            This value will always be zero unless autoCodeTextMatch in the request is true.'
          format: int32
        responsesCodedByInputId:
          type: integer
          description: 'The count of responses coded by input ID.


            This value will always be zero unless autoCodeInputId in the request is true.'
          format: int32
        responsesCodedByRegex:
          type: integer
          description: 'The count of responses coded by regular expression.


            This value will always be zero unless autoCodeByRegex in the request is true.'
          format: int32
        addedResponses:
          type: array
          items:
            $ref: '#/components/schemas/AddedResponseWithCodingInfo'
          description: The responses added to the question as a result of the POST operation.
      additionalProperties: false
      description: Returns information about the disposition of the Responses added.
    DeleteResponseResponse:
      type: object
      properties:
        errorMessage:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: Response of DeleteResponse API method
    GetResponsesResponse:
      required:
      - responses
      type: object
      properties:
        errorMessage:
          type:
          - string
          - 'null'
        responses:
          type: array
          items:
            $ref: '#/components/schemas/ExistingResponse'
          description: The requested responses in the Question.
      additionalProperties: false
      description: The response of a query to the Responses resource.
    PostResponse:
      required:
      - rid
      type: object
      properties:
        rid:
          minLength: 1
          type: string
          description: 'The respondent id, which is unique among Responses in this Question.


            This id identifies the respondent in the Study, and that respondent''s Response in this Question.'
        verbatim:
          type:
          - string
          - 'null'
          description: 'The verbatim text of the response, in other words the answer the respondent gave to the question posed.


            Required if this is a new respondent, optional if updating an existing response for this respondent.'
        translation:
          type:
          - string
          - 'null'
          description: Optional translation of the verbatim text.
        transcription:
          type:
          - string
          - 'null'
          description: Optional transcription of the response.
        notes:
          type:
          - string
          - 'null'
          description: Optional notes associated with the response.
        appliedcodes:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
          description: Array of codes to apply to the response. Note this will ignore any listed codes already applied and will not remove any.
        segmentcodes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SegmentCode'
          description: Array of segments of applied codes
      additionalProperties: false
      description: A respondent's answer to the question.
    PostResponsesBatchResponse:
      required:
      - questionResponses
      type: object
      properties:
        errorMessage:
          type:
          - string
          - 'null'
        questionResponses:
          type: array
          items:
            $ref: '#/components/schemas/AddedResponseBatchResult'
          description: Array of questions with their responses to create
      additionalProperties: false
      description: Response contains information about newly created responses in target study questions
    PutQuestionResponses:
      required:
      - questionKey
      - responses
      type: object
      properties:
        questionKey:
          type: integer
          description: Key of target question
          format: int32
        responses:
          type: array
          items:
            $ref: '#/components/schemas/PutResponseBatch'
          description: Responses
      additionalProperties: false
      description: Question's responses to put
    PostResponseBatch:
      required:
      - rid
      type: object
      properties:
        rid:
          minLength: 1
          type: string
          description: 'The respondent id, which is unique among Responses in this Question.


            This id identifies the respondent in the Study, and that respondent''s Response in this Question.'
        verbatim:
          type:
          - string
          - 'null'
          description: 'The verbatim text of the response, in other words the answer the respondent gave to the question posed.


            Required if this is a new respondent, optional if updating an existing response for this respondent.'
        translation:
          type:
          - string
          - 'null'
          description: Optional translation of the verbatim text.
        transcription:
          type:
          - string
          - 'null'
          description: Optional transcription of the response.
        notes:
          type:
          - string
          - 'null'
          description: Optional notes associated with the response.
      additionalProperties: false
      description: Response class for presenting study response data in the request for POST BATCH operation.
    DeleteResponsesBatchResponse:
      type: object
      properties:
        errorMessage:
          type:
          - string
          - 'null'
        questionResponses:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DeleteQuestionResponseResultItem'
          description: List of result items of deletion of responses
      additionalProperties: false
      description: Response contains information about which responses were deleted and which ones were not.
    PutResponsesResponse:
      required:
      - existingResponsesUnchanged
      - existingResponsesUpdated
      - responsesAdded
      - responsesCoded
      type: object
      properties:
        errorMessage:
          type:
          - string
          - 'null'
        responsesAdded:
          type: integer
          description: 'The count of Responses added to the Question.


            This is the number of responses in the PutResponsesRequest that had rid values that were not already present in this Question.'
          format: int32
        existingResponsesUpdated:
          type: integer
          description: 'The count of existing Responses updated.


            This is the number of responses in the PutResponsesRequest that had rid values that were already present in this Question,

            and for which any of the text, translation, transcription, or notes values were specified in the request and differed from the existing value in the Response.'
          format: int32
        existingResponsesUnchanged:
          type: integer
          description: 'The count of existing Responses unchanged.


            This is the number of responses in the PutResponsesRequest that had rid values that were already present in this Question,

            and for which all of the text, translation, transcription, or notes values were either not specified in the request or identical to the existing value in the Response.'
          format: int32
        responsesCoded:
          type: integer
          description: 'The count of responses coded.

            '
          format: int32
      additionalProperties: false
      description: Returns information about the disposition of the Responses added.
    ExistingResponse:
      required:
      - codeKeys
      - rid
      - text
      type: object
      properties:
        rid:
          minLength: 1
          type: string
          description: The respondent ID.
        text:
          minLength: 1
          type: string
          description: The verbatim text of the response.  In other words, the answer the respondent gave to the question.
        transcription:
          type:
          - string
          - 'null'
          description: A transcription of the response, if present for the respondent.
        translation:
          type:
          - string
          - 'null'
          description: A translation of the response, if present for the respondent.
        notes:
          type:
          - string
          - 'null'
          description: Notes associated with the response, if present for the respondent.
        codeKeys:
          type: array
          items:
            type: integer
            format: int32
          description: 'The keys of the codes applied to the response.


            Use these keys to map codes applied to a response to information about each code using the information returned by querying the Codebooks resource for the question.'
      additionalProperties: false
      description: A respondent's response stored in the question.
    DeleteResponsesBatchRequest:
      type: object
      properties:
        questionResponses:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DeleteQuestionResponses'
          description: Array of pairs of question key and respondent id
      additionalProperties: false
      description: Request contains array of pairs of question key and respondent id
    AddedResponseBatchResult:
      required:
      - addedResponses
      - questionId
      - questionKey
      type: object
      properties:
        questionKey:
          type: integer
          description: Key of target question
          format: int32
        questionId:
          type:
          - string
          - 'null'
          description: Id of target question
        addedResponses:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PostResponseBatch'
          description: Responses
      additionalProperties: false
      description: Class contains information about newly created responses for target questions
    SegmentCode:
      required:
      - codeKey
      - length
      - start
      type: object
      properties:
        codeKey:
          type: integer
          description: Key of applied code
          format: int32
        start:
          type: integer
          description: Start index of segment
          format: int32
        length:
          type: integer
          description: Segment length
          format: int32
      additionalProperties: false
      description: A descriptor class for code segment
    AddedCode:
      required:
      - codeKey
      - description
      type: object
      properties:
        codeKey:
          type: integer
          description: The key of the code, corresponding to the key of a code in the codebook.
          format: int32
        description:
          minLength: 1
          type: string
          description: The text description of the code.
      additionalProperties: false
      description: A code automatically applied to the response.
    PutResponse:
      required:
      - rid
      type: object
      properties:
        rid:
          minLength: 1
          type: string
          description: 'The respondent id, which is unique among Responses in this Question.


            This id identifies the respondent in the Study, and that respondent''s Response in this Question.'
        verbatim:
          type:
          - string
          - 'null'
          description: 'The verbatim text of the response, in other words the answer the respondent gave to the question posed.


            Required if this is a new respondent, optional if updating an existing response for this respondent.'
        translation:
          type:
          - string
          - 'null'
          description: Optional translation of the verbatim text.
        transcription:
          type:
          - string
          - 'null'
          description: Optional transcription of the response.
        notes:
          type:
          - string
          - 'null'
          description: Optional notes associated with the response.
        appliedcodes:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
          description: Array of codes to apply to the response. Note this will ignore any listed codes already applied and will not remove any.
        segmentcodes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SegmentCode'
          description: Array of segments of applied codes
      additionalProperties: false
      description: A respondent's answer to the question.
    DeleteQuestionResponses:
      type: object
      properties:
        questionKey:
          type: integer
          description: Key of question
          format: int32
        respondentIDs:
          type:
          - array
          - 'null'
          items:
            type: string
          description: Array of respondent ids to delete from the question
      additionalProperties: false
      description: Question respondents to delete.
    PostResponsesRequest:
      required:
      - responses
      type: object
      properties:
        responses:
          type: array
          items:
            $ref: '#/components/schemas/PostResponse'
          description: 'The responses to be added or updated.


            All strings in these responses will be trimmed of leading and trailing white space.'
        autoCodeTextMatch:
          type: boolean
          description: 'If true, this will attempt to AutoCode responses based on an exact (but case insensitive) text match with previously-coded responses.

            This AutoCode will execute first, followed by (if requested) Input ID matching and Regular Expression matching.'
        autoCodeInputId:
          type: boolean
          description: 'If set to True, it will attempt to Auto Code based on a code''s Input ID (Closed ends and Other Specifies only).


            This AutoCode will execute after the Text Match and before the Regular Expression match, if either is requested.'
        autoCodeByRegex:
          type: boolean
          description: 'If set to True, it will attempt to Auto Code responses via the codes'' Regular Expressions.


            This AutoCode will execute after the Text Match and Input ID match, if requested.'
      additionalProperties: false
      description: A request to add Responses to the specified Question, or to update existing Responses.
    PutResponsesBatchResponse:
      required:
      - questionResponses
      type: object
      properties:
        errorMessage:
          type:
          - string
          - 'null'
        questionResponses:
          type: array
          items:
            $ref: '#/components/schemas/PutResponsesBatchResult'
          description: Array of questions with their responses which were added/updated
      additionalProperties: false
      description: Response contains information about updated responses in target study questions
  securitySchemes:
    Bearer:
      type: http
      description: 'Please enter a valid bearer token.


        It should be in the format "bearer eyJhbGciOiJSU..."


        It will be added to the "Authentication" HTTP header'
      scheme: Bearer
      bearerFormat: JWT
