openapi: 3.2.0
info:
  title: Ascribe Coder Languages API
  description: To import this API to Postman, copy the URL from the top of this page.
  contact:
    email: support@goascribe.com
  version: v2
servers:
- url: https://api.goascribe.us/coder/v2
  description: US Servers
- url: https://api.goascribe.eu/coder/v2
  description: EU Servers
- url: https://api-ca.goascribe.com/coder/v2
  description: CA Servers
security:
- Bearer: []
tags:
- name: Languages
paths:
  /Languages/Translate:
    get:
      tags:
      - Languages
      summary: Returns the languages supported for translation
      description: 'The Code for a language is used to specify the language when translating responses.


        The Name for a language is suitable for display on a user interface.'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetLanguagesToTranslateResponse'
              example:
                languages:
                - code: en
                  name: English
                - code: de
                  name: German
                - code: fr
                  name: French
                - code: uk
                  name: Ukrainian
                errorMessage: null
            application/json:
              schema:
                $ref: '#/components/schemas/GetLanguagesToTranslateResponse'
              example:
                languages:
                - code: en
                  name: English
                - code: de
                  name: German
                - code: fr
                  name: French
                - code: uk
                  name: Ukrainian
                errorMessage: null
            text/json:
              schema:
                $ref: '#/components/schemas/GetLanguagesToTranslateResponse'
              example:
                languages:
                - code: en
                  name: English
                - code: de
                  name: German
                - code: fr
                  name: French
                - code: uk
                  name: Ukrainian
                errorMessage: null
      operationId: getLanguagesTranslate
      x-operation-id-source: derived
components:
  schemas:
    GetLanguagesToTranslateResponse:
      type: object
      properties:
        errorMessage:
          type:
          - string
          - 'null'
        languages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/NaturalLanguage'
          description: List of supported languages
      additionalProperties: false
      description: Response that contains list of languages that are supported by this API.
    NaturalLanguage:
      type: object
      properties:
        code:
          type:
          - string
          - 'null'
          description: The language code, used to specify the language in API operations.
        name:
          type:
          - string
          - 'null'
          description: The name of the language suitable for display to the user.
      additionalProperties: false
      description: A natural language supported by this API.
  securitySchemes:
    Bearer:
      type: http
      description: 'Please enter a valid bearer token.


        It should be in the format "bearer eyJhbGciOiJSU..."


        It will be added to the "Authentication" HTTP header'
      scheme: Bearer
      bearerFormat: JWT
